### ISSUE TITLE
can this be used within an iOS app to encrypt files before storing them in Dropbox?

### ISSUE THREAD

**Issue by bsabiston** [cryptomator/cryptolib-swift#7]
I'm sorry if this is not a good place to ask, but I am trying to find a way to encrypt files in an iOS app before storing them in Dropbox.  IOS provides automatic encryption for internal files I think, but if I were to export a file to Dropbox I don't think there's a way to encrypt that?  Just wondering if this library can be used for that purpose...

**Comment by tobihagemann** [comment]
Yes, this is one of the main purposes of this library. Actually, this library only deals with cryptographic functions. [cloud-access-swift](https://github.com/cryptomator/cloud-access-swift) is able to access Dropbox _and_ use [Cryptomator's encryption scheme](https://docs.cryptomator.org/en/latest/security/architecture/) to access Cryptomator vaults.

But it all depends on what you need and what you're looking for. Make sure that your project is compatible with the AGPLv3 license if you'd like to add this library to your dependencies.
